---
- name: Instalación de snapd
  apt:
    name: snapd

- name: Instalar nextcloud 
  snap:
    name: nextcloud
       
- name: Configurar nextcloud
  shell: nextcloud.manual-install "{{ usuario }}" "{{ password }}"

- name: Agregar linea a archivo de configuracion
  blockinfile:
    dest: "{{ archivo_config }}"
    insertafter: "0 => 'localhost',"
    block: |2
          1 => 'ip o dominio del servidor'